version: '3.4'

services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    container_name: ControlCentrum-mosquitto
    restart: unless-stopped
    ports:
      - "8802:8802" 
      - "8803:8803" 
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/log:/mosquitto/log:rw
  controlcentrum:
    image: ${DOCKER_REGISTRY-}controlcentrum
    restart: unless-stopped
    build:
      context: .
      dockerfile: ControlCentrum/Dockerfile
